
import Head from 'next/head'
import { useContext } from 'react'
import { AuthContext } from '../contexts/authContext'
import { useForm } from 'react-hook-form'
import { api } from '../apiLinks/axiosClientSide';
import { parseCookies } from 'nookies';
import { axiosClient } from '../apiLinks/axiosServerSide';
import styles from '../../styles/pages/Home.module.css'
import Router from 'next/router'
import Link from 'next/link'



export default function Home(props) {

    const { cancelCookie } = useContext(AuthContext);
    const { handleSubmit } = useForm();

    function logout() {

        cancelCookie();
    }



    async function deleteForm(id) {

        try {

            await api.post(`/links/${id}/delete`);
            Router.push('/home');

        } catch (error) {
            console.log(error);
        }
    }




    return (
        <div>
            <Head>
                <title>LINK CARDS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p className={styles.description}>
                    tela dinâmica com os cards
                </p>


                <div className={styles.sidebar}>
                    <div>
                        <Link href={'/form/formAdd'}>
                            <button type="submit">
                                <span> + </span>
                            </button>
                        </Link>
                    </div>
                </div>

                <div className={styles.centerArea}>
                    <div className={styles.grid}>
                        {
                            props.data.map(item => {
                                return (
                                    <div key={item._id} className={styles.card}>

                                        <li>{item.title}</li>
                                        <li>{item.content}</li>
                                        <li>{item.category}</li>
                                        <li>{item.user}</li>

                                        <div>
                                            <button
                                                type="submit"
                                                onClick={() => { deleteForm(item._id) }}>
                                                <span> delete </span>
                                            </button>
                                        </div>
                                        <div>
                                            <Link href={'/form/formAdd'}>
                                                <button type="submit">
                                                    <span> + </span>
                                                </button>
                                            </Link>
                                        </div>
                                    </div>
                                )
                            })
                        }
                    </div>
                </div>

                <div>
                    <button
                        type="submit"
                        onClick={handleSubmit(logout)}>
                        <span> logout </span>
                    </button>
                </div>
            </main>
            <footer className={styles.footer}>

                <span>colocar algo aqui como componente</span>

            </footer>
        </div>
    )
}


//pra mandar para o login após o token expirar
export async function getServerSideProps(ctx) {

    const api = axiosClient(ctx);

    const { tokenCardlink } = parseCookies(ctx);

    if (tokenCardlink) {
        return {
            redirect: {
                destination: '/'
            }
        }
    }

    const { 'data': dataForm } = await api.get('/links');

    console.log(dataForm)
    return {

        props: {
            data: dataForm
        }
    }

}
